# yamllint disable rule:comments
---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Dummy"

'on':
  push:
    branches:
      - 'renovate/**'

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Dummy job to make renovate linter happy
        run: "true"
